version: '3.5'

services:

 crdb:
   image: cockroachdb/cockroach:v21.2.4
   ports:
     - "26257:26257"
     - "8083:8080"
   command: start-single-node --insecure
   volumes:
     # WARNING: The cockroachdb will be saved to the repository.
     # The only reason for doing this is to ensure that the database is set incase
     # I have to run this code from different machines
     - "${PWD}/cockroach-data/crdb:/cockroach/cockroach-data"