version: '3.5'

services:

 crdb:
   image: cockroachdb/cockroach:v21.2.4
   ports:
     - "26257:26257"
     - "8083:8080"
   command: start-single-node --insecure
   volumes:
     - "${PWD}/cockroach-data/crdb:/cockroach/cockroach-data"